# Generated by Django 5.1.5 on 2025-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
