# Generated by Django 5.1.5 on 2025-01-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unilang', '0003_language_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='text',
            new_name='word',
        ),
    ]
